version: '3'
services:
  backend:
    image: backend-blog-app
    ports:
      - "8000:8000"
  frontend:
    image: frontend-blog-app
    ports:
      - "3000:3000"
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nudges
    expose: 
      - 5432

volumes:
  postgres_data:
  